version: 0.1
storage:
  filesystem:
    rootdirectory: /registry
  delete:
    enabled: true   
http:
  addr: 0.0.0.0:5000
auth:
  token:
    realm: http://192.168.246.146:5001/api/auth
    service: 192.168.246.146:5000
    issuer: test
    rootcertbundle: /etc/docker/registry/auth.cert
log:
  level: info 
notifications:
  endpoints:
    - name: listener
      url: http://192.168.246.146:5001/api/notification
      timeout: 5s
      threshold: 3
      backoff: 2s
